### ISSUE TITLE
v1.8.2 breaks my code - Unexpected end of input

### ISSUE THREAD

**Issue by tejo-ak** [themetalfleece/neogma#12]
Hello.
v1.8.2 breaks my code `instance.relateTo({alias:'Relationship', where{id: theId}}),`
Neo4jError: Unexpected end of input: expected whitespace or SetItem ....  ->(target) SET

it works when I revert to v1.8.1

I hope I don't need to change all of the codes for new versions.

**Comment by themetalfleece** [comment]
Thanks for reporting this bug. In `1.8.2` I had fixed something regarding relationship properties in `relateTo`, but as it seems the function didn't work if it wasn't creating any relationship properties.
This should now be fixed in `1.8.3`. I have also added a test for calling `relateTo` without any properties. I hope this didn't cause much inconvenience.
