### ISSUE TITLE
new neo4j-driver api chages

### ISSUE THREAD

**Issue by tejo-ak** [themetalfleece/neogma#23]
Hello,
I received error about `neo4j-driver/types` when having a fresh `npm install` to my project. It seems that there is new development with that library that breaking existing api.

My work around is by using `package-lock.json` from my older installation to refer to the older version of the driver

Is this a known issue?

**Comment by themetalfleece** [comment]
Thanks for reporting this, I wouldn't have caught it myself in a long time.

It seems like they changed how things are bundled, which resulted in an error when importing types from `neo4j-driver/types` instead of just `neo4j-driver`.

It seems like I have fixed it in [v.1.9.0](https://github.com/themetalfleece/neogma/releases/tag/v1.9.0) (I also upgraded `neo4j-driver` to `4.3.0`). Please let me know if this issue still persists.
