### ISSUE TITLE
Questions about primary keys and constraints

### ISSUE THREAD

**Issue by Ansis100** [themetalfleece/neogma#44]
Hi,

I am wondering if there is some way of enforcing primary key uniqueness when running a creation method multiple times? Validation does not prohibit creating nodes with identical primary keys. The only workaround (that I have found) is using `merge: true`. However, this still creates multiple relationships for the same nodes. I am also a bit confused about the examples in the docs, which create an `id` with type `string`, but Neo4j already creates id's for every node. Can we somehow use those for node identification?

Are there any other supported constraints? For example, `require`d relationships? Couldn't find any info on those.

**Comment by themetalfleece** [comment]
Hey Ansis, thanks for your message.

This kind of uniqueness can be achieved on a neo4j-level, since Neogma can't go anything for it.
For example, will a [unique index](https://neo4j.com/docs/cypher-manual/current/constraints/examples/#administration-constraints-unique-nodes) fit your case?

Regarding the `id` property in the examples, it's one we create and is different from the internal id used in neo4j. There is no way to control this, and it may be reassigned if the node is deleted. Hence, for my project I choose to assign an id of my own and use it for queries, and let the internal id by used only by neo4j. You can access this by using the `ID()` function. I recommend you read both answers in [this](https://stackoverflow.com/questions/27968827/how-to-access-the-internal-id-of-neo4j-node).
